INSERT INTO custodyService(custodianId, custodyServiceName, fee, paymentFrequency, currencyId, maxWeight, createdat)
VALUES(
    (SELECT id FROM custodian WHERE custodianName = 'Loomis'),
    'Loomis Monthly Service',
    50.00,
    'monthly',
    (SELECT id FROM currency WHERE isoCode3 = 'USD'),
    1000,
    CURRENT_TIMESTAMP);

-- Insert sample products matching the ProductSchema from @marcopersi/shared
INSERT INTO product (name, productTypeId, metalId, countryId, producerId, weight, weightUnit, purity, price, currency, year, description, imageUrl, imageFilename, inStock, stockQuantity, minimumOrderQuantity, premiumPercentage, createdat)
VALUES
    -- Gold Coins
    ('American Gold Eagle', 
     (SELECT id FROM productType WHERE productTypeName = 'Coin'), 
     (SELECT id FROM metal WHERE name = 'Gold'), 
     (SELECT id FROM country WHERE countryName = 'USA'), 
     (SELECT id FROM producer WHERE producerName = 'United States Mint'),
        31.1035, 'troy_ounces', 0.9167, 2150.50, 'USD', 2024, 'Official gold bullion coin of the United States', 'https://example.com/1-oz-American-Eagle.jpeg', '1-oz-Gold-American-Eagle.jpeg', true, 50, 1, 3.5, CURRENT_TIMESTAMP),
    ('Canadian Gold Maple Leaf', 
     (SELECT id FROM productType WHERE productTypeName = 'Coin'), 
     (SELECT id FROM metal WHERE name = 'Gold'), 
     (SELECT id FROM country WHERE countryName = 'Canada'), 
     (SELECT id FROM producer WHERE producerName = 'Royal Canadian Mint'),
        31.1035, 'troy_ounces', 0.9999, 2165.75, 'USD', 2024, 'Canadian Gold Maple Leaf coin with 99.99% purity', 'https://example.com/1-oz-Maple-Leaf.jpeg', '1-oz-Maple-Leaf.jpeg', true, 100, 1, 3.0, CURRENT_TIMESTAMP),
    ('Gold Krugerrand Coin', 
     (SELECT id FROM productType WHERE productTypeName = 'Coin'), 
     (SELECT id FROM metal WHERE name = 'Gold'), 
     (SELECT id FROM country WHERE countryName = 'South Africa'), 
     (SELECT id FROM producer WHERE producerName = 'Rand Refinery'),
        31.103, 'grams', 0.9167, 1480.00, 'USD', 2024, 'South African Gold Krugerrand coin', '', 'Rand-Krugerrand-Coin.jpg', true, 75, 1, 2.8, CURRENT_TIMESTAMP),
    ('Gold Philharmonic Coin', 
     (SELECT id FROM productType WHERE productTypeName = 'Coin'), 
     (SELECT id FROM metal WHERE name = 'Gold'), 
     (SELECT id FROM country WHERE countryName = 'Austria'), 
     (SELECT id FROM producer WHERE producerName = 'Austrian Mint'),
        31.103, 'grams', 0.9999, 1510.00, 'USD', 2024, 'Austrian Gold Philharmonic coin', '', 'Gold Vienna Philharmonic Coin.jpg', true, 50, 1, 4.0, CURRENT_TIMESTAMP),

    -- Gold Bars
    ('Gold Cast Bar 100g Valcambi', 
     (SELECT id FROM productType WHERE productTypeName = 'Cast Bar'), 
     (SELECT id FROM metal WHERE name = 'Gold'), 
     (SELECT id FROM country WHERE countryName = 'Switzerland'), 
     (SELECT id FROM producer WHERE producerName = 'Valcambi'),
        100.00, 'grams', 0.9999, 5800.00, 'USD', 2024, '100g Gold cast bar from Valcambi', '', 'Valcambi-100-Gold-Cast-Bar.jpg', true, 25, 1, 2.5, CURRENT_TIMESTAMP),
    ('Gold Minted Bar 1oz Degussa', 
     (SELECT id FROM productType WHERE productTypeName = 'Minted Bar'), 
     (SELECT id FROM metal WHERE name = 'Gold'), 
     (SELECT id FROM country WHERE countryName = 'Germany'), 
     (SELECT id FROM producer WHERE producerName = 'Degussa'),
        31.103, 'grams', 0.9999, 1520.00, 'USD', 2024, '1oz Gold minted bar from Degussa', '', '1-oz-Goldbarren-argor-heraeus.jpeg', true, 40, 1, 3.0, CURRENT_TIMESTAMP),
    ('Gold CombiBar 50g Metalor', 
     (SELECT id FROM productType WHERE productTypeName = 'CombiBar'), 
     (SELECT id FROM metal WHERE name = 'Gold'), 
     (SELECT id FROM country WHERE countryName = 'Switzerland'), 
     (SELECT id FROM producer WHERE producerName = 'Metalor'),
        50.00, 'grams', 0.9999, 2900.00, 'USD', 2024, '50g Gold CombiBar from Metalor', '', 'Metalor-Gold-50g-Bar.jpg', true, 30, 1, 3.2, CURRENT_TIMESTAMP),

    -- Silver Coins
    ('Silver Eagle Coin', 
     (SELECT id FROM productType WHERE productTypeName = 'Coin'), 
     (SELECT id FROM metal WHERE name = 'Silver'), 
     (SELECT id FROM country WHERE countryName = 'USA'), 
     (SELECT id FROM producer WHERE producerName = 'United States Mint'),
        31.103, 'grams', 0.999, 30.00, 'USD', 2024, 'American Silver Eagle coin', '', '1-oz-Silver-American-Eagle.jpeg', true, 500, 1, 15.0, CURRENT_TIMESTAMP),
    ('Silver Philharmonic Coin', 
     (SELECT id FROM productType WHERE productTypeName = 'Coin'), 
     (SELECT id FROM metal WHERE name = 'Silver'), 
     (SELECT id FROM country WHERE countryName = 'Austria'), 
     (SELECT id FROM producer WHERE producerName = 'Austrian Mint'),
        31.103, 'grams', 0.999, 32.00, 'USD', 2024, 'Austrian Silver Philharmonic coin', '', 'Silver Vienna Philharmonic Coin.jpg', true, 300, 1, 12.5, CURRENT_TIMESTAMP),

    -- Silver Bars
    ('Silver Cast Bar 1kg Valcambi', 
     (SELECT id FROM productType WHERE productTypeName = 'Cast Bar'), 
     (SELECT id FROM metal WHERE name = 'Silver'), 
     (SELECT id FROM country WHERE countryName = 'Switzerland'), 
     (SELECT id FROM producer WHERE producerName = 'Valcambi'),
        1000.00, 'grams', 0.999, 850.00, 'USD', 2024, '1kg Silver cast bar from Valcambi', '', '1-kilo-valcambi-silver-bar.jpg', true, 100, 1, 5.0, CURRENT_TIMESTAMP),

    -- Palladium Products
    ('Palladium Maple Leaf Coin', 
     (SELECT id FROM productType WHERE productTypeName = 'Coin'), 
     (SELECT id FROM metal WHERE name = 'Palladium'), 
     (SELECT id FROM country WHERE countryName = 'Canada'), 
     (SELECT id FROM producer WHERE producerName = 'Royal Canadian Mint'),
        31.103, 'grams', 0.9995, 1100.00, 'USD', 2024, 'Canadian Palladium Maple Leaf coin', '', 'Palladium-Maple-Leaf-Coin.jpg', true, 20, 1, 6.0, CURRENT_TIMESTAMP),

    ('Palladium Cast Bar 100g Argor', 
     (SELECT id FROM productType WHERE productTypeName = 'Cast Bar'), 
     (SELECT id FROM metal WHERE name = 'Palladium'), 
     (SELECT id FROM country WHERE countryName = 'Switzerland'), 
     (SELECT id FROM producer WHERE producerName = 'Argor-Heraeus'),
        100.00, 'grams', 0.9995, 4100.00, 'USD', 2024, '100g Palladium cast bar from Argor-Heraeus', '', '100-Palladium-cast-bar-argor.png', true, 15, 1, 4.5, CURRENT_TIMESTAMP),

    -- Platinum Products
    ('Platinum Kangaroo Coin', 
     (SELECT id FROM productType WHERE productTypeName = 'Coin'), 
     (SELECT id FROM metal WHERE name = 'Platinum'), 
     (SELECT id FROM country WHERE countryName = 'Australia'), 
     (SELECT id FROM producer WHERE producerName = 'Perth Mint'),
        31.103, 'grams', 0.9995, 1000.00, 'USD', 2024, 'Australian Platinum Kangaroo coin', '', 'Platinum-Kangaroo-Coin.png', true, 25, 1, 5.5, CURRENT_TIMESTAMP),

    ('Platinum Cast Bar 50g Valcambi', 
     (SELECT id FROM productType WHERE productTypeName = 'Cast Bar'), 
     (SELECT id FROM metal WHERE name = 'Platinum'), 
     (SELECT id FROM country WHERE countryName = 'Switzerland'), 
     (SELECT id FROM producer WHERE producerName = 'Valcambi'),
        50.00, 'grams', 0.9995, 2600.00, 'USD', 2024, '50g Platinum cast bar from Valcambi', '', '1-oz-platinum-bar-royal-canadian-mint.png', true, 20, 1, 4.8, CURRENT_TIMESTAMP);